# Generated by Django 4.2.13 on 2024-07-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_item_description_remove_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='blood_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='civil_status',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='elementary_school',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='father_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='high_school',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mother_occupation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='place_of_birth',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='senior_high_school',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
