# Generated by Django 4.2.13 on 2024-07-08 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_blood_type_item_civil_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='contact_num',
        ),
        migrations.AddField(
            model_name='item',
            name='college',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
