# Generated by Django 4.2.13 on 2024-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_item_contact_num_item_college'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='address',
            new_name='permanent_address',
        ),
        migrations.RemoveField(
            model_name='item',
            name='phone',
        ),
        migrations.AddField(
            model_name='item',
            name='citizenship',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='mobile_phone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='residential_address',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='zipcode',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
